# Generated by Django 2.2.24 on 2022-10-10 18:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('subject', '0023_auto_20211124_1722'),
    ]

    operations = [
        migrations.CreateModel(
            name='Track',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('double_majors', models.ManyToManyField(related_name='double_majors', to='subject.Department')),
                ('major', models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, related_name='major', to='subject.Department')),
                ('minors', models.ManyToManyField(related_name='minors', to='subject.Department')),
                ('specialized_majors', models.ManyToManyField(related_name='specialized_majors', to='subject.Department')),
            ],
        ),
    ]
