# Generated by Django 2.2.24 on 2022-05-09 08:49

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('subject', '0023_auto_20211124_1722'),
        ('session', '0009_auto_20210911_0624'),
    ]

    operations = [
        migrations.CreateModel(
            name='BasicGraduationRequirement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entrance_from', models.IntegerField(validators=[django.core.validators.MinValueValidator(1900), django.core.validators.MaxValueValidator(9999)])),
                ('entrance_to', models.IntegerField(validators=[django.core.validators.MinValueValidator(1900), django.core.validators.MaxValueValidator(9999)])),
                ('total_credit', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(999)])),
                ('mandatory_basic', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(200)])),
                ('mandatory_general', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(200)])),
                ('mandatory_general_au', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(200)])),
                ('elective_hss', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(200)])),
                ('research', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(200)])),
            ],
        ),
        migrations.CreateModel(
            name='MajorGraduationRequirement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entrance_from', models.IntegerField(validators=[django.core.validators.MinValueValidator(1900), django.core.validators.MaxValueValidator(9999)])),
                ('entrance_to', models.IntegerField(validators=[django.core.validators.MinValueValidator(1900), django.core.validators.MaxValueValidator(9999)])),
                ('major_type', models.CharField(choices=[('MAJOR', 'major'), ('DOUBLE_MAJOR', 'double_major'), ('MINOR', 'minor'), ('SPECIALIZED_MAJOR', 'specialized_major'), ('SELF_DESIGNED_MAJOR', 'self_designed_major')], max_length=30)),
                ('mandatory_major', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(200)])),
                ('elective_major', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(200)])),
                ('elective_basic', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(200)])),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='subject.Department')),
            ],
        ),
        migrations.CreateModel(
            name='Planner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entrance_year', models.IntegerField(db_index=True)),
                ('basic_graduation_requirement', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='planner.BasicGraduationRequirement')),
                ('major_graduation_requirements', models.ManyToManyField(related_name='graduation_requirement_user_set', to='planner.MajorGraduationRequirement')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='session.UserProfile')),
            ],
        ),
        migrations.CreateModel(
            name='RequiredCourseSet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('MAJOR_REQUIRED', 'major_required'), ('MAJOR_ELECTIVE', 'major_elective'), ('BASIC_ELECTIVE', 'basic_elective')], max_length=20)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='required_course_set_course', to='subject.Course')),
                ('graduation_requirement', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='planner.MajorGraduationRequirement')),
            ],
        ),
        migrations.CreateModel(
            name='RecognizedCourse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_course', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='recognized_course_original_course', to='subject.Course')),
                ('recognized_course', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='recognized_course_recognized_course', to='subject.Course')),
            ],
        ),
        migrations.CreateModel(
            name='PlannerItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(db_index=True)),
                ('semester', models.IntegerField(db_index=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='subject.Course')),
                ('planner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='planner.Planner')),
            ],
        ),
        migrations.AddField(
            model_name='majorgraduationrequirement',
            name='recognized_courses',
            field=models.ManyToManyField(related_name='recognized_course_user_set', to='planner.RecognizedCourse'),
        ),
    ]
