# Generated by Django 2.2.28 on 2023-03-18 19:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0003_auto_20230319_0415'),
    ]

    operations = [
        migrations.RenameField(
            model_name='planner',
            old_name='entrance_year',
            new_name='start_year',
        ),
        migrations.AlterField(
            model_name='planner',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='planners', to='session.UserProfile'),
        ),
    ]
