# Generated by Django 2.2.28 on 2023-03-18 19:23

from django.db import migrations, models


def set_order(apps, schema_editor):
    Planner = apps.get_model('planner', 'Planner')
    for u, in Planner.objects.values_list('user'):
        arrange_order = 0
        for p in Planner.objects.filter(user=u):
            p.arrange_order = arrange_order
            p.save()
            arrange_order += 1


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0004_auto_20230319_0420'),
    ]

    operations = [
        migrations.AddField(
            model_name='planner',
            name='arrange_order',
            field=models.SmallIntegerField(db_index=True, default=0),
            preserve_default=False,
        ),
        migrations.RunPython(
            set_order,
            reverse_code=migrations.RunPython.noop,
        ),
    ]
