# Generated by Django 2.2.28 on 2023-03-18 19:27

from django.db import migrations, models


def set_end_year(apps, schema_editor):
    Planner = apps.get_model('planner', 'Planner')
    for p in Planner.objects.all():
        p.end_year = p.start_year + 3
        p.save()


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0005_planner_arrange_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='planner',
            name='end_year',
            field=models.IntegerField(db_index=True, default=2100),
            preserve_default=False,
        ),
        migrations.RunPython(
            set_end_year,
            reverse_code=migrations.RunPython.noop,
        ),
    ]
