# Generated by Django 2.2.28 on 2023-03-18 19:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('subject', '0023_auto_20211124_1722'),
        ('planner', '0006_planner_end_year'),
    ]

    operations = [
        migrations.CreateModel(
            name='FuturePlannerItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(db_index=True)),
                ('semester', models.IntegerField(db_index=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='subject.Course')),
                ('planner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='future_items', to='planner.Planner')),
            ],
        ),
        migrations.DeleteModel(
            name='PlannerItem',
        ),
    ]
