# Generated by Django 2.2.28 on 2023-03-18 19:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('subject', '0023_auto_20211124_1722'),
        ('planner', '0007_auto_20230319_0436'),
    ]

    operations = [
        migrations.CreateModel(
            name='TakenPlannerItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lecture', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='subject.Lecture')),
                ('planner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='taken_items', to='planner.Planner')),
            ],
        ),
        migrations.CreateModel(
            name='GenericPlannerItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('planner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='generic_items', to='planner.Planner')),
            ],
        ),
    ]
