# Generated by Django 2.2.28 on 2023-03-21 09:54

from django.db import migrations, models
import django.db.models.deletion

from apps.graduation.models import GeneralTrack, MajorTrack
from apps.subject.models import Department


def get_default_general_track():
    track, created = GeneralTrack.objects.get_or_create(start_year=2018, end_year=2022, is_foreign=False,
                                                        total_credit=136, total_au=8,
                                                        basic_required=23, basic_elective=9,
                                                        thesis_study=3, thesis_study_doublemajor=0,
                                                        general_required_credit=7, general_required_au=8,
                                                        humanities=21, humanities_doublemajor=12)
    return track.pk

def get_default_major_track():
    track, created = MajorTrack.objects.get_or_create(start_year=2016, end_year=2100,
                                                      department=list(Department.objects.filter(code="CS"))[-1],
                                                      basic_elective_doublemajor=3,
                                                      major_required=19, major_elective=30)
    return track.pk

class Migration(migrations.Migration):

    dependencies = [
        ('graduation', '0001_initial'),
        ('planner', '0008_genericplanneritem_takenplanneritem'),
    ]

    operations = [
        migrations.AddField(
            model_name='planner',
            name='additional_tracks',
            field=models.ManyToManyField(to='graduation.AdditionalTrack'),
        ),
        migrations.AddField(
            model_name='planner',
            name='general_track',
            field=models.ForeignKey(default=get_default_general_track, on_delete=django.db.models.deletion.PROTECT, to='graduation.GeneralTrack'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='planner',
            name='major_track',
            field=models.ForeignKey(default=get_default_major_track, on_delete=django.db.models.deletion.PROTECT, to='graduation.MajorTrack'),
            preserve_default=False,
        ),
    ]
