# Generated by Django 2.2.28 on 2023-03-29 17:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subject', '0023_auto_20211124_1722'),
        ('planner', '0009_auto_20230321_1854'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='takenplanneritem',
            unique_together={('planner', 'lecture')},
        ),
    ]
