# Generated by Django 2.2.28 on 2023-03-30 12:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0010_auto_20230330_0205'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='GenericPlannerItem',
            new_name='ArbitraryPlannerItem',
        ),
    ]
