# Generated by Django 2.2.28 on 2023-03-30 12:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0011_auto_20230330_2112'),
    ]

    operations = [
        migrations.AlterField(
            model_name='arbitraryplanneritem',
            name='planner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='arbitrary_items', to='planner.Planner'),
        ),
    ]
