# Generated by Django 2.2.28 on 2023-04-04 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0013_auto_20230401_1522'),
    ]

    operations = [
        migrations.AddField(
            model_name='arbitraryplanneritem',
            name='is_excluded',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='futureplanneritem',
            name='is_excluded',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='takenplanneritem',
            name='is_excluded',
            field=models.BooleanField(default=False),
        ),
    ]
