version: '3.4'

services:
  back:
    depends_on: 
      - db
    container_name: otlplus-back
    platform: linux/amd64
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    tty: true
    ports:
      - "58000:8000"
    volumes:
      - ./volumes/scripts:/var/www/otlplus/scripts
      - ./volumes/config:/root/.ssh/config
      - ./volumes/key.pem:/root/key.pem
      - ./volumes/logs:/var/www/otlplus/logs
    working_dir: /var/www/otlplus
    command: gunicorn otlplus.wsgi --bind 0.0.0.0:8000
