[tool.pytest.ini_options]
DJANGO_SETTINGS_MODULE = "otlplus.settings"
python_files = "test_*.py"
addopts = "--reuse-db"

[tool.coverage.report]
include = ["apps/**/*"]
omit = ["**/migrations/*", "**/__init__.py"]
