# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-23 15:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('session', '0001_initial'),
        ('subject', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.CharField(max_length=65536)),
                ('grade', models.SmallIntegerField(default=0)),
                ('load', models.SmallIntegerField(default=0)),
                ('speech', models.SmallIntegerField(default=0)),
                ('total', models.FloatField(default=0.0)),
                ('writer_label', models.CharField(default='\ubb34\ud559\uacfc \ub119\uc8fd\uc774', max_length=200)),
                ('written_datetime', models.DateTimeField(auto_now=True, db_index=True)),
                ('like', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='CommentVote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_up', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='LiberalBestComment',
            fields=[
                ('comment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='liberal_best_comment', serialize=False, to='review.Comment')),
            ],
        ),
        migrations.CreateModel(
            name='MajorBestComment',
            fields=[
                ('comment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='major_best_comment', serialize=False, to='review.Comment')),
            ],
        ),
        migrations.AddField(
            model_name='commentvote',
            name='comment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment_vote', to='review.Comment'),
        ),
        migrations.AddField(
            model_name='commentvote',
            name='userprofile',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='comment_vote', to='session.UserProfile'),
        ),
        migrations.AddField(
            model_name='comment',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='subject.Course'),
        ),
        migrations.AddField(
            model_name='comment',
            name='lecture',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='subject.Lecture'),
        ),
        migrations.AddField(
            model_name='comment',
            name='writer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='comment_set', to='session.UserProfile'),
        ),
    ]
