# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2018-12-28 08:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0002_comment_is_deleted'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='comment',
            unique_together=set([('writer', 'lecture')]),
        ),
    ]
