# -*- coding: utf-8 -*-
# Generated by Django 1.11.21 on 2020-01-04 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0004_auto_20200104_2351'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='written_datetime',
            field=models.DateTimeField(auto_now_add=True, db_index=True, null=True),
        ),
    ]
