# -*- coding: utf-8 -*-
# Generated by Django 1.11.21 on 2020-01-04 14:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('session', '0004_auto_20180301_2046'),
        ('review', '0005_comment_written_datetime'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='commentvote',
            unique_together=set([('comment', 'userprofile')]),
        ),
    ]
