# -*- coding: utf-8 -*-
# Generated by Django 1.11.21 on 2020-01-23 07:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0006_auto_20200104_2357'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Comment',
            new_name='Review',
        ),
    ]
