# -*- coding: utf-8 -*-
# Generated by Django 1.11.21 on 2020-01-23 07:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0008_auto_20200123_1643'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='LiberalBestComment',
            new_name='HumanityBestReview',
        ),
        migrations.RenameModel(
            old_name='MajorBestComment',
            new_name='MajorBestReview',
        ),
        migrations.RenameModel(
            old_name='CommentVote',
            new_name='ReviewVote',
        ),
    ]
