# -*- coding: utf-8 -*-
# Generated by Django 1.11.21 on 2020-01-23 07:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0009_auto_20200123_1647'),
    ]

    operations = [
        migrations.RenameField(
            model_name='humanitybestreview',
            old_name='comment',
            new_name='review',
        ),
        migrations.RenameField(
            model_name='majorbestreview',
            old_name='comment',
            new_name='review',
        ),
    ]
