# -*- coding: utf-8 -*-
# Generated by Django 1.11.21 on 2020-01-23 08:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0011_auto_20200123_1701'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviewvote',
            name='review',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='review.Review'),
        ),
        migrations.AlterField(
            model_name='reviewvote',
            name='userprofile',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='review_votes', to='session.UserProfile'),
        ),
    ]
