# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2020-05-26 07:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0014_auto_20200123_1744'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reviewvote',
            name='is_up',
        ),
    ]
