# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2020-07-04 11:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0015_remove_reviewvote_is_up'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reviews', to='subject.Course'),
        ),
        migrations.AlterField(
            model_name='review',
            name='lecture',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reviews', to='subject.Lecture'),
        ),
    ]
