# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2021-07-31 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0018_auto_20200913_1915'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviewvote',
            name='created_datetime',
            field=models.DateTimeField(auto_now_add=True, db_index=True, null=True),
        ),
    ]
