const courses = [
  {
    id: 3678,
    old_code: 'CBE342',
    department: { code: 'CBE', name: '생명화학공학과', name_en: '' },
    title: '화학 및 생물 제품디자인',
    title_en: 'Chemical and Biological Product Design',
    type: '전공선택',
    type_en: 'Major Elective',
    summary: '등록되지 않았습니다.',
    review_total_weight: 0,
    related_courses_prior: [],
    related_courses_posterior: [],
    professors: [
      { professor_id: 695, name: '장용근', name_en: '' },
      { professor_id: 708, name: '박승빈', name_en: '' },
    ],
    grade: 0,
    load: 0,
    speech: 0,
    userspecific_is_read: false,
  },
  {
    id: 295,
    old_code: 'CBE441',
    department: { code: 'CBE', name: '생명화학공학과', name_en: '' },
    title: '공정 및 제품 디자인',
    title_en: 'Techniques of Process and Product Design',
    type: '전공선택',
    type_en: 'Major Elective',
    summary:
      '학부생을 대상으로 화학 및 생물 제품의 설계에 필요한 기초 개념을 강의한다. 제품의 필요성 분석(Need),제품 아이디어 도출 및 스크리닝, 특허 검색, 제품의 기본 사양(specification) 도출, 상품화를 위한 전략 도출 등을 다룬다. (선수과목:  CBE221, CBE303, CBE311, CBE332 중 세 과목 이상 수강)',
    review_total_weight: 0,
    related_courses_prior: [],
    related_courses_posterior: [],
    professors: [
      { professor_id: 1853, name: '이재우', name_en: '' },
      { professor_id: 695, name: '장용근', name_en: '' },
    ],
    grade: 0,
    speech: 0,
    load: 0,
    userspecific_is_read: false,
  },
  {
    id: 1599,
    old_code: 'CBE442',
    department: { code: 'CBE', name: '생명화학공학과', name_en: '' },
    title: '생명화학공학 디자인 프로젝트',
    title_en: 'Chemical and Biomolecular Engineering Capstone Design Project',
    type: '전공필수',
    type_en: 'Major Required',
    summary:
      '생명 및 화학산업 동향, 기업의 회계 및 재무제표, 최적화의 개념, 경제성 평가, 공정 및 상품의 설계방법에대하여 강의하고, 공정설계 및 상품설계의 case study를 다룬다. (선수과목:  CBE202, CBE221, CBE321)',
    review_total_weight: 4,
    related_courses_prior: [],
    related_courses_posterior: [],
    professors: [
      { professor_id: 1853, name: '이재우', name_en: '' },
      { professor_id: 2023, name: '리섕', name_en: '' },
      { professor_id: 628, name: '박선원', name_en: '' },
      { professor_id: 539, name: '이태용', name_en: '' },
      { professor_id: 2140, name: '김현욱', name_en: '' },
    ],
    grade: 15,
    load: 6,
    speech: 12,
    userspecific_is_read: false,
  },
];

export default courses;
