const user = {
  departments: [],
  email: 'mini@sparcs.org',
  favorite_departments: [],
  firstName: '동혁',
  id: 1,
  lastName: '김',
  majors: [{
    id: 1,
    name: '산업디자인학과',
    name_en: 'industrial design',
    code: 'industrial',
  }],
  my_timetable_lectures: [],
  review_writable_lectures: [{
    class_no: 'C',
    class_title: 'C',
    class_title_en: 'C',
    classtimes: [],
    code: '21.120',
    common_title: '일반생물학',
    common_title_en: 'General Biology',
    course: 40,
    credit: 3,
    credit_au: 0,
    department: 132,
    department_code: 'BS',
    department_name: '생명과학과',
    department_name_en: 'Biological Sciences',
    examtimes: [],
    grade: 0,
    id: 1848419,
    is_english: true,
    limit: 45,
    load: 0,
    num_classes: 3,
    num_labs: 0,
    num_people: 50,
    old_code: 'BS120',
    professors: [],
    review_total_weight: 0,
    semester: 3,
    speech: 0,
    title: '일반생물학',
    title_en: 'General Biology',
    type: '기초필수',
    type_en: 'Basic Required',
    year: 2021,
  }],
  reviews: [],
  student_id: '20200104',
};

export default user;
