# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-03-27 07:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('subject', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExamTime',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.SmallIntegerField(choices=[(0, '\uc6d4'), (1, '\ud654'), (2, '\uc218'), (3, '\ubaa9'), (4, '\uae08'), (5, '\ud1a0'), (6, '\uc77c')])),
                ('begin', models.TimeField()),
                ('end', models.TimeField()),
                ('lecture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='examtime_set', to='subject.Lecture')),
            ],
        ),
        migrations.AddField(
            model_name='classtime',
            name='lecture',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='classtime_set', to='subject.Lecture'),
        ),
    ]
