# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-12-19 17:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('subject', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassTime',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.SmallIntegerField(choices=[(0, '\uc6d4'), (1, '\ud654'), (2, '\uc218'), (3, '\ubaa9'), (4, '\uae08'), (5, '\ud1a0'), (6, '\uc77c')])),
                ('begin', models.TimeField()),
                ('end', models.TimeField()),
                ('type', models.CharField(choices=[(b'l', '\uac15\uc758'), (b'e', '\uc2e4\ud5d8')], max_length=1)),
                ('building', models.CharField(blank=True, max_length=10, null=True)),
                ('roomName', models.CharField(blank=True, max_length=60, null=True)),
                ('roomName_en', models.CharField(blank=True, max_length=60, null=True)),
                ('roomNum', models.CharField(max_length=20, null=True)),
                ('unit_time', models.SmallIntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ExamTime',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.SmallIntegerField(choices=[(0, '\uc6d4'), (1, '\ud654'), (2, '\uc218'), (3, '\ubaa9'), (4, '\uae08'), (5, '\ud1a0'), (6, '\uc77c')])),
                ('begin', models.TimeField()),
                ('end', models.TimeField()),
            ],
        ),
        migrations.AddField(
            model_name='lecture',
            name='class_title',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='lecture',
            name='class_title_en',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='lecture',
            name='common_title',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='lecture',
            name='common_title_en',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='lecture',
            name='syllabus',
            field=models.CharField(blank=True, max_length=260, null=True),
        ),
        migrations.AddField(
            model_name='examtime',
            name='lecture',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='examtime_set', to='subject.Lecture'),
        ),
        migrations.AddField(
            model_name='classtime',
            name='lecture',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='classtime_set', to='subject.Lecture'),
        ),
    ]
