# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-07-01 08:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('subject', '0003_auto_20170628_1050'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseByProf',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courseByProf', to='subject.Course')),
                ('lectures', models.ManyToManyField(related_name='courseByProf', to='subject.Lecture')),
                ('professor', models.ManyToManyField(related_name='courseByprof', to='subject.Professor')),
            ],
        ),
    ]
