# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2018-11-08 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subject', '0003_remove_lecture_syllabus'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='related_courses_posterior',
            field=models.ManyToManyField(related_name='_course_related_courses_posterior_+', to='subject.Course'),
        ),
        migrations.AddField(
            model_name='course',
            name='related_courses_prior',
            field=models.ManyToManyField(related_name='_course_related_courses_prior_+', to='subject.Course'),
        ),
    ]
