# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-07-01 09:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subject', '0004_coursebyprof'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coursebyprof',
            name='course',
        ),
        migrations.RemoveField(
            model_name='coursebyprof',
            name='lectures',
        ),
        migrations.RemoveField(
            model_name='coursebyprof',
            name='professor',
        ),
        migrations.DeleteModel(
            name='CourseByProf',
        ),
    ]
