# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-07-01 12:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subject', '0005_auto_20170701_1821'),
    ]

    operations = [
        migrations.RenameField(
            model_name='classtime',
            old_name='roomName_ko',
            new_name='roomName',
        ),
        migrations.AddField(
            model_name='classtime',
            name='roomNum_en',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
