# -*- coding: utf-8 -*-
# Generated by Django 1.11.21 on 2019-12-30 11:44

from django.db import migrations, models
from django.utils import timezone


class Migration(migrations.Migration):

    dependencies = [
        ('subject', '0006_auto_20191229_1607'),
    ]

    operations = [
        migrations.AddField(
            model_name='semester',
            name='courseDesciptionSubmission',
            field=models.DateTimeField(default=timezone.now()),
            preserve_default=False,
        ),
    ]
