# -*- coding: utf-8 -*-
# Generated by Django 1.11.21 on 2019-12-31 04:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subject', '0007_semester_coursedesciptionsubmission'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lecture',
            old_name='professor',
            new_name='professors',
        ),
    ]
