# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-09-05 06:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subject', '0008_auto_20170701_2204'),
    ]

    operations = [
        migrations.AddField(
            model_name='lecture',
            name='class_title',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='lecture',
            name='class_title_en',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='lecture',
            name='common_title',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='lecture',
            name='common_title_en',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
