# -*- coding: utf-8 -*-
# Generated by Django 1.11.21 on 2020-01-06 16:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('session', '0004_auto_20180301_2046'),
        ('subject', '0008_auto_20191231_1335'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courseuser',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='read_users_courseuser', to='subject.Course'),
        ),
        migrations.AlterUniqueTogether(
            name='courseuser',
            unique_together=set([('course', 'user_profile')]),
        ),
    ]
