# -*- coding: utf-8 -*-
# Generated by Django 1.11.21 on 2020-01-13 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subject', '0010_auto_20200108_0427'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lecture',
            name='deleted',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
