# -*- coding: utf-8 -*-
# Generated by Django 1.11.21 on 2020-01-23 08:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subject', '0012_auto_20200113_1609'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='comment_num',
            new_name='review_num',
        ),
        migrations.RenameField(
            model_name='lecture',
            old_name='comment_num',
            new_name='review_num',
        ),
        migrations.RenameField(
            model_name='professor',
            old_name='comment_num',
            new_name='review_num',
        ),
    ]
