# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2020-09-13 09:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subject', '0017_auto_20200905_1957'),
    ]

    operations = [
        migrations.RenameField(
            model_name='classtime',
            old_name='building',
            new_name='building_id',
        ),
        migrations.RenameField(
            model_name='classtime',
            old_name='roomName',
            new_name='building_name',
        ),
        migrations.RenameField(
            model_name='classtime',
            old_name='roomName_en',
            new_name='building_name_en',
        ),
        migrations.RenameField(
            model_name='classtime',
            old_name='roomNum',
            new_name='room_name',
        ),
    ]
