# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2020-09-13 09:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subject', '0018_auto_20200913_1845'),
    ]

    operations = [
        migrations.RenameField(
            model_name='classtime',
            old_name='building_name',
            new_name='building_full_name',
        ),
        migrations.RenameField(
            model_name='classtime',
            old_name='building_name_en',
            new_name='building_full_name_en',
        ),
    ]
