# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2021-04-27 08:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subject', '0020_auto_20200913_1915'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='review_num',
            new_name='review_total_weight',
        ),
        migrations.RenameField(
            model_name='lecture',
            old_name='review_num',
            new_name='review_total_weight',
        ),
        migrations.RenameField(
            model_name='professor',
            old_name='review_num',
            new_name='review_total_weight',
        ),
    ]
