# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2021-06-26 07:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subject', '0021_auto_20210427_1708'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classtime',
            name='type',
            field=models.CharField(choices=[('l', '강의'), ('e', '실험')], max_length=1),
        ),
        migrations.AlterField(
            model_name='course',
            name='summury',
            field=models.CharField(default='', max_length=4000),
        ),
    ]
