# Generated by Django 2.2.24 on 2021-11-24 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subject', '0022_auto_20210626_1620'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='grade_sum',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='course',
            name='load_sum',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='course',
            name='review_total_weight',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='course',
            name='speech_sum',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='lecture',
            name='grade_sum',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='lecture',
            name='load_sum',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='lecture',
            name='review_total_weight',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='lecture',
            name='speech_sum',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='professor',
            name='grade_sum',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='professor',
            name='load_sum',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='professor',
            name='review_total_weight',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='professor',
            name='speech_sum',
            field=models.FloatField(default=0),
        ),
    ]
