# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-12-19 17:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('session', '0003_auto_20171220_0243'),
        ('subject', '0002_auto_20171220_0243'),
    ]

    operations = [
        migrations.CreateModel(
            name='OldTimeTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.CharField(max_length=10)),
                ('year', models.IntegerField(null=True)),
                ('semester', models.SmallIntegerField(null=True)),
                ('table_no', models.SmallIntegerField(null=True)),
                ('lecture', models.ManyToManyField(to='subject.Lecture')),
            ],
        ),
        migrations.CreateModel(
            name='TimeTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(null=True)),
                ('semester', models.SmallIntegerField(null=True)),
                ('table_id', models.SmallIntegerField(null=True)),
                ('lecture', models.ManyToManyField(to='subject.Lecture')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timetable_set', to='session.UserProfile')),
            ],
        ),
        migrations.CreateModel(
            name='Wishlist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lectures', models.ManyToManyField(to='subject.Lecture')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='wishlist_set', to='session.UserProfile')),
            ],
        ),
    ]
