# -*- coding: utf-8 -*-
# Generated by Django 1.11.21 on 2020-01-13 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0002_remove_timetable_table_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timetable',
            name='semester',
            field=models.SmallIntegerField(db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='timetable',
            name='year',
            field=models.IntegerField(db_index=True, null=True),
        ),
    ]
