# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2020-09-06 08:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0003_auto_20200113_1609'),
    ]

    operations = [
        migrations.RenameField(
            model_name='oldtimetable',
            old_name='lecture',
            new_name='lectures',
        ),
        migrations.RenameField(
            model_name='timetable',
            old_name='lecture',
            new_name='lectures',
        ),
    ]
