# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2020-09-06 08:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0004_auto_20200906_1747'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timetable',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timetables', to='session.UserProfile'),
        ),
        migrations.AlterField(
            model_name='wishlist',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='wishlist', to='session.UserProfile'),
        ),
    ]
