# Generated by Django 2.2.24 on 2022-01-23 08:45

from django.db import migrations, models


def set_order(apps, schema_editor):
    Timetable = apps.get_model('timetable', 'Timetable')
    for u, y, s in Timetable.objects.values_list('user', 'year', 'semester'):
        arrange_order = 0
        for t in Timetable.objects.filter(user=u, year=y, semester=s):
            t.arrange_order = arrange_order
            t.save()
            arrange_order += 1


class Migration(migrations.Migration):

    dependencies = [
        ('session', '0009_auto_20210911_0624'),
        ('timetable', '0005_auto_20200906_1749'),
    ]

    operations = [
        migrations.AddField(
            model_name='timetable',
            name='arrange_order',
            field=models.SmallIntegerField(db_index=True, default=0),
            preserve_default=False,
        ),
        migrations.RunPython(
            set_order,
            reverse_code=migrations.RunPython.noop,
        ),
    ]
