# Generated by Django 2.2.28 on 2024-02-08 07:34

from django.db import migrations, models

from apps.timetable.models import Timetable


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0006_auto_20220123_1745'),
    ]

    def generate_default_name(apps, schema_editor):
        for timetable in Timetable.objects.all():
            timetable.name = f'table {timetable.arrange_order + 1}'
            timetable.save()

    operations = [
        migrations.AddField(
            model_name='timetable',
            name='name',
            field=models.CharField(max_length=20),
            preserve_default=False,
        ),
        migrations.RunPython(generate_default_name)
    ]
