# Generated by Django 2.2.24 on 2022-01-23 09:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('session', '0009_auto_20210911_0624'),
        ('timetable', '0006_auto_20220123_1745'),
    ]

    operations = [
        migrations.RenameField(
            model_name='timetable',
            old_name='order',
            new_name='arrange_order',
        ),
        migrations.AlterUniqueTogether(
            name='timetable',
            unique_together={('user', 'year', 'semester', 'arrange_order')},
        ),
    ]
