# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-03-27 07:59
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('subject', '0002_auto_20170327_1659'),
        ('session', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlockColor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('semester', models.SmallIntegerField()),
                ('color', models.IntegerField()),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='subject.Course')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='userprofile',
            name='majors',
            field=models.ManyToManyField(related_name='major_user_set', to='subject.Department'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='minors',
            field=models.ManyToManyField(related_name='minor_user_set', to='subject.Department'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='specialized_major',
            field=models.ManyToManyField(related_name='specialized_major_user_set', to='subject.Department'),
        ),
    ]
