# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-12-19 17:43

from django.db import migrations, models
from ..fields import CredentialsField


class Migration(migrations.Migration):

    dependencies = [
        ('subject', '0002_auto_20171220_0243'),
        ('session', '0002_auto_20160924_0011'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='email',
            field=models.EmailField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='google_calendar_id',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='google_credential',
            field=CredentialsField(null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='majors',
            field=models.ManyToManyField(related_name='major_user_set', to='subject.Department'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='minors',
            field=models.ManyToManyField(related_name='minor_user_set', to='subject.Department'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='specialized_major',
            field=models.ManyToManyField(related_name='specialized_major_user_set', to='subject.Department'),
        ),
    ]
