# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-05-01 13:46
from __future__ import unicode_literals

from django.db import migrations
import oauth2client.contrib.django_util.models


class Migration(migrations.Migration):

    dependencies = [
        ('session', '0002_auto_20170327_1659'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='google_credential',
            field=oauth2client.contrib.django_util.models.CredentialsField(null=True),
        ),
    ]
