# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2018-03-01 11:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('session', '0003_auto_20171220_0243'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blockcolor',
            name='course',
        ),
        migrations.RemoveField(
            model_name='blockcolor',
            name='user',
        ),
        migrations.DeleteModel(
            name='BlockColor',
        ),
    ]
