# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2020-09-13 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('session', '0007_auto_20200913_1916'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='taken_lectures',
            field=models.ManyToManyField(blank=True, related_name='taken_users', to='subject.Lecture'),
        ),
    ]
