# Generated by Django 2.2.28 on 2023-03-21 08:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('subject', '0023_auto_20211124_1722'),
    ]

    operations = [
        migrations.CreateModel(
            name='GeneralTrack',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_year', models.IntegerField(db_index=True)),
                ('end_year', models.IntegerField(db_index=True)),
                ('is_foreign', models.BooleanField(db_index=True)),
                ('total_credit', models.IntegerField()),
                ('total_au', models.IntegerField()),
                ('basic_required', models.IntegerField()),
                ('basic_elective', models.IntegerField()),
                ('thesis_study', models.IntegerField()),
                ('thesis_study_doublemajor', models.IntegerField()),
                ('general_required_credit', models.IntegerField()),
                ('general_required_au', models.IntegerField()),
                ('humanities', models.IntegerField()),
                ('humanities_doublemajor', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='MajorTrack',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_year', models.IntegerField(db_index=True)),
                ('end_year', models.IntegerField(db_index=True)),
                ('basic_elective_doublemajor', models.IntegerField()),
                ('major_required', models.IntegerField()),
                ('major_elective', models.IntegerField()),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='subject.Department')),
            ],
        ),
        migrations.CreateModel(
            name='AdditionalTrack',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_year', models.IntegerField(db_index=True)),
                ('end_year', models.IntegerField(db_index=True)),
                ('type', models.CharField(choices=[('DOUBLE', 'DOUBLE'), ('MINOR', 'MINOR'), ('ADVANCED', 'ADVANCED'), ('INTERDISCIPLINARY', 'INTERDISCIPLINARY')], db_index=True, max_length=32)),
                ('major_required', models.IntegerField()),
                ('major_elective', models.IntegerField()),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='subject.Department')),
            ],
        ),
    ]
