# -*- coding: utf-8 -*-
# Generated by Django 1.11.21 on 2020-01-03 10:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('subject', '0008_auto_20191231_1335'),
        ('review', '0003_auto_20181228_1757'),
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FamousReviewDailyFeed',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('priority', models.FloatField()),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='subject.Department')),
                ('reviews', models.ManyToManyField(to='review.Comment')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='famousreviewdailyfeed',
            unique_together=set([('date', 'department')]),
        ),
    ]
