# -*- coding: utf-8 -*-
# Generated by Django 1.11.21 on 2020-01-03 12:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('subject', '0008_auto_20191231_1335'),
        ('session', '0004_auto_20180301_2046'),
        ('main', '0002_auto_20200103_1913'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReviewWriteDailyUserFeed',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('priority', models.FloatField()),
                ('lecture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='subject.Lecture')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='session.UserProfile')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='reviewwritedailyuserfeed',
            unique_together=set([('date', 'user')]),
        ),
    ]
