# -*- coding: utf-8 -*-
# Generated by Django 1.11.21 on 2020-01-05 16:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20200103_2118'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='FamousReviewDailyFeed',
            new_name='FamousMajorReviewDailyFeed',
        ),
    ]
