# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2020-07-04 11:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20200304_2348'),
    ]

    operations = [
        migrations.AlterField(
            model_name='famousmajorreviewdailyfeed',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='subject.Department'),
        ),
        migrations.AlterField(
            model_name='randomcoursereco',
            name='lecture',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='subject.Lecture'),
        ),
        migrations.AlterField(
            model_name='relatedcoursedailyuserfeed',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='subject.Course'),
        ),
        migrations.AlterField(
            model_name='reviewwritedailyuserfeed',
            name='lecture',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='subject.Lecture'),
        ),
    ]
