# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2020-10-02 13:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_auto_20200704_2014'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='randomcoursereco',
            name='lecture',
        ),
        migrations.RemoveField(
            model_name='randomcoursereco',
            name='userprofile',
        ),
        migrations.DeleteModel(
            name='RandomCourseReco',
        ),
    ]
