# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2021-01-12 16:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('session', '0008_auto_20200913_1916'),
        ('main', '0011_auto_20201008_2300'),
    ]

    operations = [
        migrations.CreateModel(
            name='RateDailyUserFeed',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('priority', models.FloatField()),
                ('visible', models.BooleanField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='session.UserProfile')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='ratedailyuserfeed',
            unique_together=set([('date', 'user')]),
        ),
    ]
