# Generated by Django 2.2.24 on 2021-09-04 20:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_auto_20210808_1724'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rankedreviewdailyfeed',
            name='semester',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='subject.Semester'),
        ),
    ]
