name: CI

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]

jobs:
  front-build:
    name: Front-end Build
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./react

    steps:
      - uses: actions/checkout@v3
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 14
          cache: npm
          cache-dependency-path: react/package-lock.json
      - name: Install npm dependencies
        run: npm ci
      - name: Build
        run: npm run build
  
  front-test:
    name: Front-end Test
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./react

    steps:
      - uses: actions/checkout@v3
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 14
          cache: npm
          cache-dependency-path: react/package-lock.json
      - name: Install npm dependencies
        run: npm ci
      - name: Run tests
        run: npm t

  back-test:
    name: Back-end Test
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.8
          cache: 'pip'
      - name: Install dependencies
        run: pip install -r requirements.txt 
      - name: Run tests
        run: pytest tests/   
